#!/bin/bash

# With the addition of Keystone, to use an openstack cloud you should
# authenticate against keystone, which returns a **Token** and **Service
# Catalog**.  The catalog contains the endpoint for all services the
# user/tenant has access to - including nova, glance, keystone, swift.
#
# *NOTE*: Using the 2.0 *auth api* does not mean that compute api is 2.0.  We
# will use the 1.1 *compute api*
export OS_AUTH_URL=https://identity.api.rackspacecloud.com/v2.0/

# OS_TENANT_ID is left blank on purpose because it interferes with swift client
# working.
export OS_TENANT_ID=" "
# export OS_TENANT_NAME="service"

# In addition to the owning entity (tenant), openstack stores the entity
# performing the action as the **user**.
echo -n "Please enter your Openstack Username: "
read OS_USERNAME
export OS_USERNAME=$OS_USERNAME

# With Keystone you pass the keystone password.
echo -n "Please enter your OpenStack Password: "
read -s OS_PASSWORD_INPUT
export OS_PASSWORD=$OS_PASSWORD_INPUT
echo

# os-region-name
echo -n "Please enter your Region (ORD, DFW, IAD, SYD): "
read OS_REGION_NAME
export OS_REGION_NAME=$OS_REGION_NAME

# HEAT Tenant ID, needed to make this work.
echo -n "Please enter HEAT tenant ID: "
read HEAT_TENANT_ID
export HEAT_TENANT_ID=${HEAT_TENANT_ID}
export HEAT_URL=https://api.rs-heat.com/v1/${HEAT_TENANT_ID}/

